services:
  - type: web
    name: genrefy
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn genrefy_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: genrefydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: LASTFM_API_KEY
        sync: false
      - key: LASTFM_SHARED_SECRET
        sync: false

databases:
  - name: genrefydb
    plan: free