services:
  - type: web
    name: genrefy
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn genrefy_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://vilyad:450Y2byBqTLtMNjyFDmdxnaMlwlxZGqk@dpg-d5ib91ogjchc73amfso0-a/genrefydb"
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DEBUG
        value: false